bkp sep24

diff --git a/mediciones/mu_parada_linea b/mediciones/mu_parada_linea
--- a/mediciones/mu_parada_linea
+++ b/mediciones/mu_parada_linea
@@ -1,34 +1,37 @@
-# =====================================================
-# Calcula el lambda de llegada de personas a una parada
-# =====================================================
+# =========================================================
+# Calcula el mu de la cant personas que suben en una parada
+# =========================================================
 
 parada=$1
+linea=$2
 
 if [ ! "$parada" ]; then
   echo "error, indicar parada">&2
   exit 1
 fi
 
-./selecciona mediciones.txt -parada $parada | awk -F, '{
+if [ ! "$linea" ]; then
+  echo "error, indicar linea">&2
+  exit 1
+fi
+
+./selecciona mediciones.txt -parada $parada -linea $linea | awk -F, '{
 
   hora=$5
   suben=$7
-  cpers=$9
 
   if (NR==1) {
     # Inicialización de variables
     # ---------------------------
-    ant_hora=hora;cant_suben=0;cant_quedan=cpers
+    ant_hora=hora;cant_suben=0
   } 
 
   if (hora==ant_hora) { # Junto mediciones de la misma hora
     cant_suben+=suben
-    if (cpers<cant_quedan) cant_quedan=cpers
   } else {
-    print ant_hora","cant_suben","cant_quedan
+    print ant_hora","cant_suben
     ant_hora=hora
     cant_suben=suben
-    cant_quedan=cpers
   }
 } 
 END {
@@ -36,23 +39,18 @@ END {
 }' | awk -F, -v parada=$parada '{
   hora=$1
   suben=$2
-  cpers=$3
   if (NR==1) {
     ant_hora=hora
     ant_suben=suben
-    ant_cpers=cpers
     lambda=0
     cant=0
   } else {
     dif_hora=hora-ant_hora
-    llegaron=cpers+suben-ant_cpers
-    lambda+=llegaron/dif_hora
+    mu+=suben/dif_hora
     cant++
     ant_hora=hora
     ant_suben=suben
-    ant_cpers=cpers
   }  
 } END {
-  #print "lambda_parada_"parada"="(lambda/cant)" (en pers/segundo)."
-  print (lambda/cant)
+  print "mu_parada_"parada"_linea_"linea"="(mu/cant)"."
 }'
